### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by thomasgauvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#158]
As a user, I would like to be able to browse the application in french, so that I can understand how to use the application as a french-speaker.

Acceptance criteria:
Given that I am on the hamburger menu,
and that I toggled the French button

then I should see,

- The menu, step-by-step directions, buttons, and application text written in French
- Data from services and departments, as they are static names from the University, written in English (not translated)

Story tasks:

- [x] Add language preference to side menu

- [x] Change static text based on the preferences

- [x] Change Google Maps directions to French, either there is a Google Maps setting to get directions in French, or we will have to use Google Translate

- [ ] Testing
