### ISSUE TITLE
Indoor details map 

### ISSUE THREAD

**Issue by tarekait1996** [Concordia-Campus-Guide/Concordia-Campus-Guide#22]
As a user, I would like to be able to see the inner map of Concordia’s buildings, so that I can clearly see what is on each of the floors of the building.
--

Acceptance criteria:
Given that I am using the map,and that I click on an over layered building,and that I choose to see the indoor map of the building from the info cards,then, I should be able to:
1) see an indoor map of the selected building 
2) switch between floors inside the building
--

Story tasks:
- [ ] Figure out a standardized way of displaying indoor map information 
- [ ] Add button to building info card to go to "Indoor Map" view
- [ ] Display indoor maps and floors on the application
- [ ] Testing
