### ISSUE TITLE
Get floor plans

### ISSUE THREAD

**Issue by thomasgauvin** [Concordia-Campus-Guide/Concordia-Campus-Guide#23]
As a developer, I would like to be able to get the floor plan data, so that I can accomplish user story for indoor map details #22 

This story includes floorplans for tunnels between campus buildings.

Acceptance criteria:
1. Prioritize: EV, Hall, JMSB, Faubourg (priority 1) + tunnels
2. All the buildings, all the floors (priority 2) + tunnels

Story tasks:
- [ ] Get floor plans for priority 1 buildings
- [ ] Get floor plans for priority 2 buildings

**Comment by viveanban** [comment]
These are some of the interesting/useful links that I found related to this issue:
- [Use indoor maps to view floor plans](https://support.google.com/maps/answer/2803784?hl=en&visit_id=637146608205879094-203247097&rd=1&co=GENIE.Platform%3DDesktop&oco=1)
- [uploading floor plan videos](https://www.youtube.com/watch?v=XNvFjX9t-Zk&app=desktop)
- [actual link to add floor plans to googlemaps](https://maps.google.com/floorplans/myfloors)

**Comment by viveanban** [comment]
Sat Feb 15 Meeting Notes:
Chosen maps: 
[floor_plans_chosen.zip](https://github.com/Concordia-Campus-Guide/Concordia-Campus-Guide/files/4208671/floor_plans_chosen.zip)

- [ ] get pictures of the real floorplans and their numbers
- [ ] add the rooms to the floorplans (by hand at least)

**Comment by narrapangan** [comment]
<img width="544" alt="vl-1" src="https://user-images.githubusercontent.com/32281531/74596490-e84f3480-501d-11ea-8687-a6b22755a397.png">

<img width="528" alt="vl-2" src="https://user-images.githubusercontent.com/32281531/74596489-e4bbad80-501d-11ea-948f-1fb86f950abf.png">

Could we ask him if we need to know whether each room is actually accessible by students/staff/etc? It might be too detailed. Could we also ask him if we could restrict the possibilities to washrooms, larger classrooms, etc? 

Thanks!

**Comment by CarenRizk** [comment]
![image](https://user-images.githubusercontent.com/34378319/74682657-a268ac80-5194-11ea-84c4-578d94d5173f.png)

![image](https://user-images.githubusercontent.com/34378319/74682673-b3192280-5194-11ea-9fe9-1b9207a2a95f.png)
