### ISSUE TITLE
Visualize Campus map

### ISSUE THREAD

**Issue by tarekait1996** [Concordia-Campus-Guide/Concordia-Campus-Guide#3]
As a user, I would like to see the maps of my surroundings, and easily see the Concordia Loyola Campus or the SGW Campus, so that I can visualize campus surroundings. 

Acceptance Criteria:
- See the map
- Be able to easily switch between the campuses.

Subtasks:
- [x] Integrate Google Map API
- [x] Implementing the Map interface (outdoor)
- [x] Switch between campuses
- [ ] Testing

**Comment by viveanban** [comment]
Add an overlay on the Concordia buildings to distinguish them [not necessarily an outline].
